version: "3.8"

services:
  web:
    container_name: "web"
    image: web
    build: .
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - net
  db:
    container_name: "db"
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - net

volumes:
  postgres:
networks:
  net:
    driver: bridge